-- AlterTable
ALTER TABLE `MODELO_FREELANCER` ADD COLUMN `peso` DECIMAL(5, 2) NULL;
ALTER TABLE `MODELO_FREELANCER` ADD COLUMN `sapato` INTEGER NULL;
ALTER TABLE `MODELO_FREELANCER` ADD COLUMN `roupa` INTEGER NULL;
ALTER TABLE `MODELO_FREELANCER` ADD COLUMN `cabelo` VARCHAR(50) NULL;
ALTER TABLE `MODELO_FREELANCER` ADD COLUMN `olhos` VARCHAR(50) NULL;
ALTER TABLE `MODELO_FREELANCER` ADD COLUMN `idade` INTEGER NULL;
ALTER TABLE `MODELO_FREELANCER` ADD COLUMN `nacionalidade` VARCHAR(50) NULL;
ALTER TABLE `MODELO_FREELANCER` ADD COLUMN `experiencia` TEXT NULL;
ALTER TABLE `MODELO_FREELANCER` ADD COLUMN `habilidades` TEXT NULL;
